# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jimm2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 283)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setToolTipDuration(32)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.scale_root_combo = QtWidgets.QComboBox(self.centralwidget)
        self.scale_root_combo.setMinimumSize(QtCore.QSize(250, 0))
        self.scale_root_combo.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scale_root_combo.setObjectName("scale_root_combo")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.scale_root_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scale_root_combo)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.scale_combo = QtWidgets.QComboBox(self.centralwidget)
        self.scale_combo.setMinimumSize(QtCore.QSize(250, 0))
        self.scale_combo.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scale_combo.setObjectName("scale_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scale_combo)
        self.bypass_button = QtWidgets.QCheckBox(self.centralwidget)
        self.bypass_button.setObjectName("bypass_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bypass_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMaximumSize(QtCore.QSize(250, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.voices_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.voices_spin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.voices_spin.setReadOnly(False)
        self.voices_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.voices_spin.setMinimum(1)
        self.voices_spin.setMaximum(16)
        self.voices_spin.setProperty("value", 16)
        self.voices_spin.setObjectName("voices_spin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.voices_spin)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.midi_input_combo = QtWidgets.QComboBox(self.centralwidget)
        self.midi_input_combo.setMinimumSize(QtCore.QSize(250, 0))
        self.midi_input_combo.setMaximumSize(QtCore.QSize(250, 16777215))
        self.midi_input_combo.setObjectName("midi_input_combo")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.midi_input_combo)
        self.refresh_midi_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_midi_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.refresh_midi_button.setObjectName("refresh_midi_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.refresh_midi_button)
        self.horizontalLayout.addLayout(self.formLayout)
        self.messages_tree = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messages_tree.sizePolicy().hasHeightForWidth())
        self.messages_tree.setSizePolicy(sizePolicy)
        self.messages_tree.setMinimumSize(QtCore.QSize(720, 0))
        self.messages_tree.setAlternatingRowColors(True)
        self.messages_tree.setObjectName("messages_tree")
        self.horizontalLayout.addWidget(self.messages_tree)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Root"))
        self.scale_root_combo.setItemText(0, _translate("MainWindow", "C"))
        self.scale_root_combo.setItemText(1, _translate("MainWindow", "C# / Db"))
        self.scale_root_combo.setItemText(2, _translate("MainWindow", "D"))
        self.scale_root_combo.setItemText(3, _translate("MainWindow", "D# / Eb"))
        self.scale_root_combo.setItemText(4, _translate("MainWindow", "E"))
        self.scale_root_combo.setItemText(5, _translate("MainWindow", "F"))
        self.scale_root_combo.setItemText(6, _translate("MainWindow", "F# / Gb"))
        self.scale_root_combo.setItemText(7, _translate("MainWindow", "G"))
        self.scale_root_combo.setItemText(8, _translate("MainWindow", "G# / Ab"))
        self.scale_root_combo.setItemText(9, _translate("MainWindow", "A"))
        self.scale_root_combo.setItemText(10, _translate("MainWindow", "A# / Bb"))
        self.scale_root_combo.setItemText(11, _translate("MainWindow", "B"))
        self.label_5.setText(_translate("MainWindow", "Scale"))
        self.bypass_button.setText(_translate("MainWindow", "Bypass"))
        self.label_7.setText(_translate("MainWindow", "Voices"))
        self.label_8.setText(_translate("MainWindow", "MIDI In"))
        self.refresh_midi_button.setText(_translate("MainWindow", "Refresh"))

